#pragma once

#include "crdt/Buffer.h"
#include "crdt/EditStrategy.h"
#include <functional>
#include <optional>
#include <queue>
#include <random>
#include <string>
#include <vector>

namespace CollabText::Crdt {

struct NetworkConfig {
    uint32_t min_latency_ms = 50;
    uint32_t max_latency_ms = 200;
    double duplicate_probability = 0.05;
    bool allow_reorder = true;
};

struct ScheduledOp {
    uint64_t deliver_at_ms = 0;
    uint16_t from_replica = 0;
    Operation op;

    bool operator>(const ScheduledOp& other) const {
        return deliver_at_ms > other.deliver_at_ms;
    }
};

class NetworkSim {
public:
    NetworkSim(int num_replicas, NetworkConfig config, uint64_t seed);

    /// Apply a local edit on a replica and broadcast to all online peers.
    Operation edit(int replica,
                   const std::vector<std::pair<uint32_t, uint32_t>>& ranges,
                   const std::vector<std::string>& new_text);

    /// Apply an edit generated by a strategy.
    Operation edit(int replica, const EditAction& action);

    /// Undo/redo on a replica and broadcast to all online peers.
    std::optional<Operation> undo(int replica);
    std::optional<Operation> redo(int replica);

    /// Mark a replica as offline.
    void disconnect(int replica);

    /// Bring a replica back online.
    void reconnect(int replica);

    /// Advance the simulated clock by ms milliseconds, delivering due ops.
    void tick(uint64_t ms);

    /// Deliver ALL pending ops, retry deferred.
    void drain();

    /// Check invariants on all replicas (calls QFAIL on failure).
    void check_all_invariants(const char* context) const;

    /// Assert all replicas have converged (same visible text).
    void assert_convergence(const char* context) const;

    /// Run collect_garbage on a specific replica.
    size_t collect_garbage(int replica);

    /// Compute watermark = meet(all replica versions) and compact all.
    size_t compact_all();

    /// Access a replica's buffer.
    const Buffer& buffer(int replica) const;
    Buffer& buffer(int replica);

    /// Number of replicas.
    int num_replicas() const;

    /// Current simulated clock.
    uint64_t clock() const;

private:
    void broadcast(int source, const Operation& op);
    uint64_t random_latency();

    using OpQueue = std::priority_queue<ScheduledOp,
                                        std::vector<ScheduledOp>,
                                        std::greater<ScheduledOp>>;

    std::vector<Buffer> m_replicas;
    std::vector<OpQueue> m_queues;          // per-replica inbox
    std::vector<bool> m_offline;
    std::vector<std::vector<ScheduledOp>> m_pending_offline;  // ops queued while offline
    uint64_t m_clock = 0;
    NetworkConfig m_config;
    std::mt19937 m_rng;
};

} // namespace CollabText::Crdt
